apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: auth
type: Opaque
stringData:
  POSTGRES_USER: auth
  POSTGRES_PASSWORD: authpass
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest
